apiVersion: v1
baseDomain: ntnxlab.local
additionalTrustBundle: | 
    -----BEGIN CERTIFICATE-----
    MIIFrDCCA5QCCQCJz5JhcXwimjANBgkqhkiG9w0BAQsFADCBlzELMAkGA1UEBhMC
    SlAxDjAMBgNVBAgMBUNoaWJhMRAwDgYDVQQHDAdLYXNoaXdhMQ0wCwYDVQQKDARu
    dG54MRAwDgYDVQQLDAdudG54bGFiMRYwFAYDVQQDDA1udG54bGFiLmxvY2FsMS0w
    KwYJKoZIhvcNAQkBFh5sYWtzaG1pLmJhbGFyYW1hbmVAbnV0YW5peC5jb20wHhcN
    MjIwOTIwMDM0NDU3WhcNMjUwNzEwMDM0NDU3WjCBlzELMAkGA1UEBhMCSlAxDjAM
    BgNVBAgMBUNoaWJhMRAwDgYDVQQHDAdLYXNoaXdhMQ0wCwYDVQQKDARudG54MRAw
    DgYDVQQLDAdudG54bGFiMRYwFAYDVQQDDA1udG54bGFiLmxvY2FsMS0wKwYJKoZI
    hvcNAQkBFh5sYWtzaG1pLmJhbGFyYW1hbmVAbnV0YW5peC5jb20wggIiMA0GCSqG
    SIb3DQEBAQUAA4ICDwAwggIKAoICAQC9+sEikrTktx48c1YPnjNoKS+75jVEYPHK
    cbRYbhHeYho2scmGUU/TVWenM6YqxOR8ubRFan/QgTsENMe6OH2uMm0Pytk/T17u
    I3dzN09Ot6jopIb8G4RMrz7MkwRwO6XSg69H5GZpRDsA94Y0uRMU4PwfhdgGwmnB
    Nh0+14iJ+zELDf8kpksLRImaGObW2GVd34StVTPlVi+IBxjEo52Ruzqm7vGcGeSB
    bfkP9CIPwmmpffPdMGavCuztsg/aAN4vbQ2L/sllprbkdnkQqX83sybjUgn33lZZ
    U+MctfCKVos0+8DQA7FbYRJVeo6metXAsphvlqvDlSls6TFzoSQfzF3ELnLRsOuU
    FkgVYIZyPN6ztl/T0sSThAeMD4dm8PHfOBpxIOsKg6eOU4pEUlFMR42c2qpgz0YG
    iNIPkfNLI/OghBiTi3tXm3lczT2MKLJLjoUljZzceQ1twtgVQtVrcSKOkodR3B2b
    6A+6xFghtWeqU5vfQTlVxzw0TcF1OIbGjUC2hAbXqZtRNO8C4r3uuMrhR3u6mGOf
    UKZ2YspPN5ApE+Uc1nFvz7MyShhFBJA3v/ZT/wTUu9CcCzhUiWpGTi9/+YKMWVVx
    681u6Szb9LLz8bxqO0YzMPjs7zZWQOCnnxL1usWE8Cgn0cRO7hZwQJGIT+s3K2hm
    IMl3/iBxuwIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQAKMjHXVJTeii6VeyIp0HhM
    astDFf/JLLXd/t2Ad4JTrFrUazv6KU1LD/VvEj5X2GpsowgyK/+RMOZ67yVgMCqX
    y67g4Cfp7E3lODeZes61rEDQyylXquH/5R7KlQcaE5s0v1KyFYPhGmOWantv3FHO
    lJWtFnLgu7lTx5WV4YmrsPG/tZ0U3Gu9ytybkW3AmKruaVj6c7zjlRiGM+j2Q69f
    U2glOnGNpMmLw0cqgcNdkY9umq2YWpyQQ2Zqifboef7ru9uv9G7sb9MqtC9f4T+B
    hGNOddSMA7Ad8/W/tIiwKcH2jxE1qCKWWzrG6zt2/mnys5FOYQ7GMGnzcfSmo4rj
    Ak5Xtkp3n+lAWr718Z091yY0eRRzkwooiv/bSx9Mma7xqkgOy9/OGvW6lLwjp7CU
    bl2l337IU0KqPz5ByGIwUP/AVctLqx+Jc28t5UZt+AgjFBJ9T6QPrwof4wkGN/11
    tmW9zcZM1w2yHPmHeR+xy4tZSddkIU+jsq4eVOggA/LEIX8D9QMiMl6gRqdMTQgP
    eGakgMZJioOHtQ73Tcch1ZacMT97NydA6SaSMDh0r7Be9StJevAYM/t7LAK1cDHh
    OWNh0ACeImMsmimh1mVeKQYvP3ia1VbEQBFOZVnNghAs7oO/Zig74jnlb2mRJElj
    C71757IxYik5WX1ISN5CaA==
    -----END CERTIFICATE-----
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
credentialsMode: Manual
metadata:
  creationTimestamp: null
  name: xyz
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.38.18.192/26
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  nutanix:
    apiVIP: 10.38.18.251
    ingressVIP: 10.38.18.252
    prismCentral:
      endpoint:
        address: pc.ntnxlab.local
        port: 9440
      password: techX2020!
      username: admin
    prismElements:
    - endpoint:
        address: 10.38.18.199
        port: 9440
      uuid: 0005e93a-3b29-fa1a-6b84-ac1f6b6922d1
    subnetUUIDs:
    - 34c84ddf-6c6e-46bf-9a5c-617b0b08a92c
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZjk2ZWVkY2JiMDdiNDk2M2I0NDMzYTc0OGY0OWI4NGI6RllSVzdTMzlNMEQwOURVWEhDWkdMSlYzUkRISE5OUVJBUUtUTFQyOEhKVkUzSDlWS0UzQVVCNVNFVTE2UUNSRA==","email":"lakshmi.balaramane@nutanix.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZjk2ZWVkY2JiMDdiNDk2M2I0NDMzYTc0OGY0OWI4NGI6RllSVzdTMzlNMEQwOURVWEhDWkdMSlYzUkRISE5OUVJBUUtUTFQyOEhKVkUzSDlWS0UzQVVCNVNFVTE2UUNSRA==","email":"lakshmi.balaramane@nutanix.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTFiNTM3OTlhLWQ4YTgtNDZmMi1iOGUyLThiNGNhMmU4N2RhZTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTNZalExWXpjMk0yWm1ObUkwWm1Fd09USXlZbU0zWWpkak9EUXpaVE13T1NKOS5OM0NSOE1BUU82SGpZY1hBQ1hCd3dJWUNhRTZCN1Ewc1JSZUxIZ0xPQTZXZ0w2UVdYQUIxLXUxa3A5UkNaLUFQR3loQTI3Rm43Mjc5UFQ3MzRjQThjb1pvZjdFRTRPNlRaa3hXZEhab251NXBCRHRvd0VQNnFra3JJU3JMemVOUmhQNUliNHk1TEVpaU1mSnByc2p5NmRYZXI3eXJsemVpamZDVUJaLU1pVXhJYmM4YkpTSGNMOTUtNC0tbHF1emVOaWpaY3JqVXh2d2JwckM0cHljdzl2NGY2WS1uYzFyZUtnOTlaeGRLTDhaTDdQOW9UTFRRWGg4WUVnX1R3WW9qYVNKbzFONWZPUUNKTnd4aUtPTUg5T3Q3aFozRmxELW1FQTFTQkZ1MXVaRGJKVFowNGZUSHMwSk9uLUZGYll6UFN4SWlBV1NZc2JIR29vRW5ZMGVLcW16MzhQcDlseWVCNUlfdGJPb0xjeFV1cml0eE1ZTWFNUklhRTc3dFdnei0xdnFrdXc2dm9rOENtUEtHT0ppbEwwTVh2UGVTeHN2MU83ODNNUGtuR256X1dJb1R6RzhHRDFkNHZHMFhpSEpvRzdmSWZpd2szMmhmampndVJCdFBfTml5OVl0NEZIMHpoQTZxRGNxNkNyMUxBOUt0ZWJxTUNQSjhUUHZMZEpsVUtHdDZzSE5UVHg0elRMX0JZcEZjR1JPQTNrVXg4REpLaU9HWURkQ3JkMTI0dnR4UkY4NWR0THRPLUoxOXVabUxEcHpxYzc0WENvbVZhNkhYNnl4SVhDbnBjV1hLbWk4d3E3RHhlQWJiM1BuLVJ0R2NRb25fOGV3VmVHMThzSzVUTFcxWUVLeDJDNGJ4cmJncjNaYUxVRnNvblA5RWEwZmVrZVNNalg1QTBVYw==","email":"lakshmi.balaramane@nutanix.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTFiNTM3OTlhLWQ4YTgtNDZmMi1iOGUyLThiNGNhMmU4N2RhZTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTNZalExWXpjMk0yWm1ObUkwWm1Fd09USXlZbU0zWWpkak9EUXpaVE13T1NKOS5OM0NSOE1BUU82SGpZY1hBQ1hCd3dJWUNhRTZCN1Ewc1JSZUxIZ0xPQTZXZ0w2UVdYQUIxLXUxa3A5UkNaLUFQR3loQTI3Rm43Mjc5UFQ3MzRjQThjb1pvZjdFRTRPNlRaa3hXZEhab251NXBCRHRvd0VQNnFra3JJU3JMemVOUmhQNUliNHk1TEVpaU1mSnByc2p5NmRYZXI3eXJsemVpamZDVUJaLU1pVXhJYmM4YkpTSGNMOTUtNC0tbHF1emVOaWpaY3JqVXh2d2JwckM0cHljdzl2NGY2WS1uYzFyZUtnOTlaeGRLTDhaTDdQOW9UTFRRWGg4WUVnX1R3WW9qYVNKbzFONWZPUUNKTnd4aUtPTUg5T3Q3aFozRmxELW1FQTFTQkZ1MXVaRGJKVFowNGZUSHMwSk9uLUZGYll6UFN4SWlBV1NZc2JIR29vRW5ZMGVLcW16MzhQcDlseWVCNUlfdGJPb0xjeFV1cml0eE1ZTWFNUklhRTc3dFdnei0xdnFrdXc2dm9rOENtUEtHT0ppbEwwTVh2UGVTeHN2MU83ODNNUGtuR256X1dJb1R6RzhHRDFkNHZHMFhpSEpvRzdmSWZpd2szMmhmampndVJCdFBfTml5OVl0NEZIMHpoQTZxRGNxNkNyMUxBOUt0ZWJxTUNQSjhUUHZMZEpsVUtHdDZzSE5UVHg0elRMX0JZcEZjR1JPQTNrVXg4REpLaU9HWURkQ3JkMTI0dnR4UkY4NWR0THRPLUoxOXVabUxEcHpxYzc0WENvbVZhNkhYNnl4SVhDbnBjV1hLbWk4d3E3RHhlQWJiM1BuLVJ0R2NRb25fOGV3VmVHMThzSzVUTFcxWUVLeDJDNGJ4cmJncjNaYUxVRnNvblA5RWEwZmVrZVNNalg1QTBVYw==","email":"lakshmi.balaramane@nutanix.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyFvxcraY3k4FitK1etPGU6sZMYo7W4qG0EF6TUV94RJjDjqlbUXflzdAwIi1vHGPbuS6Zd1sEFMldHPmOAuNTul82nmSoSRhmaBp2fkMJogYBz+7EiFNTrjkGRTBIcBW3MuWC1iXu0yEKrLbK0QOQw/Ss07ADOCoiOtyoa8wVNwE0oQQUOTtbh1Q4IEOiSZw+jA6pi7PrZG0BJQsfyRp0isntur6x7ZGuhqi2yFgBAAIv7Eq3fUMY+3zwbadwbJ5H2te47IerRBXkK4y9nDP5yVcejjW3bODXqQasc7Fw+DFJXb4LT5MNsMh3z6MAvaTVWJmZ69ElcyVoU6ey//6R